import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import FooterFb from "./components/flowbite-react/FooterFb";
import { GeneralContext } from "./context/GeneralContext";
import NavbarTwo from "./components/Navbar/NavbarTwo";

// const inter = Inter({ subsets: ["latin"], weight: "400" });

const montserrat = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Inet Beringer - Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.className} dark`}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
                localStorage.setItem("reachedBottom", "false");
                localStorage.setItem("reachedTop", "false");
              `,
          }}
        />
      </head>
      <GeneralContext>
        <body className="bg-blob overflow-x-hidden">
          {children}
          {/* <Footer /> */}
        </body>
      </GeneralContext>
    </html>
  );
}
